export const columns = [
  { id: 'ExtractionDate', label: 'ExtractionDate' },
  { id: 'Market', label: 'Market' },
  { id: 'Source', label: 'Source' },
  { id: 'Level1Category', label: 'Level1Category' },
  { id: 'Level2Category', label: 'Level2Category' },
  { id: 'Level3Category', label: 'Level3Category' },
  { id: 'SKU', label: 'SKU' },
  { id: 'Title', label: 'Title', minWidth: 100 },
  { id: 'TitleKeywords', label: 'TitleKeywords' },
  { id: 'Brand', label: 'Brand' },
  {
    id: 'Copy',
    label: 'Copy',
    minWidth: 200,
    format: (value) => (value ? value.substr(0, 150) + '...' : value),
  },
  { id: 'CopyKeywords', label: 'CopyKeywords' },
  { id: 'Availability', label: 'Availability' },
  { id: 'Color', label: 'Color' },
  { id: 'Memory', label: 'Memory' },
  { id: 'Currency', label: 'Currency' },
  { id: 'Price', label: 'Price' },
  { id: 'OldPrice', label: 'OldPrice' },
  { id: 'Rating', label: 'Rating' },
  { id: 'Reviews', label: 'Reviews' },
  { id: 'HeroImage', label: 'HeroImage' },
  { id: 'GalleryImages', label: 'GalleryImages' },
  { id: 'GalleryImagesCount', label: 'GalleryImagesCount' },
  { id: 'GalleryVideosCount', label: 'GalleryVideosCount' },
  { id: 'InpageImages', label: 'InpageImages' },
  { id: 'InpageImagesCount', label: 'InpageImagesCount' },
  { id: 'InpageVideosCount', label: 'InpageVideosCount' },
  { id: 'PageNumber', label: 'PageNumber' },
  { id: 'PositionOnPage', label: 'PositionOnPage' },
  { id: 'Shelf', label: 'Shelf' },
  {
    id: 'RecommendedProducts',
    label: 'RecommendedProducts',
    minWidth: 250,
    format: (value) => (value ? value.substr(0, 150) + '...' : value),
  },
  {
    id: 'Specifications',
    label: 'Specifications',
    minWidth: 250,
    format: (value) => (value ? value.substr(0, 150) + '...' : value),
  },
  { id: 'URL', label: 'URL' },
];
